# a matrix list of variables used in the container build process
include:
  - from_image_name: "ghcr.io/alexchay/python-base"
    from_image_tag: "3.10-slim"
    image_name: "python"
    image_tag: "3.10-slim"
  - from_image_name: "ghcr.io/alexchay/python-base"
    from_image_tag: "3.11-slim"
    image_name: "python"
    image_tag: "3.11-slim"
