# a matrix list of variables used in the container build process
include:
  - base_image_name: "ghcr.io/alexchay/python-base"
    base_image_tag: "3.10-slim"
    image_name: "python"
    image_tags: "3.10-slim, 3.10"
  - base_image_name: "ghcr.io/alexchay/python-base"
    base_image_tag: "3.11-slim"
    image_name: "python"
    image_tags: "3.11-slim, 3.11"
  - base_image_name: "ghcr.io/alexchay/python-base"
    base_image_tag: "3.12-slim"
    image_name: "python"
    image_tags: "3.12-slim, 3.12"
