# a matrix list of variables used in the container build process
include:
  - PYTHON_VERSION: "3.10"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.10-slim"
    BUILD_IMAGE_NAME: "python"
    BUILD_IMAGE_TAGS: "3.10-slim,3.10,3.10_2025.07.31.0"
  - PYTHON_VERSION: "3.11"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.11-slim"
    BUILD_IMAGE_NAME: "python"
    BUILD_IMAGE_TAGS: "3.11-slim,3.11,3.11_2025.07.31.0"
  - PYTHON_VERSION: "3.12"
    BASE_IMAGE_NAME: ghcr.io/alexchay/python-base
    BASE_IMAGE_TAG: "3.12-slim"
    BUILD_IMAGE_NAME: "python"
    BUILD_IMAGE_TAGS: "3.12-slim,3.12,3.12_2025.07.31.0,2025.07.31.0"
