[build-system]

[tool.poetry]
name = "docker-python"
version = "2025.05.17.0"
description = ""
readme = "README.md"
authors = ["Alexander Chaykovskiy <alexchay@gmail.com>"]
license = "MIT"
repository = "https://github.com/alexchay/docker-python"
homepage = "https://github.com/alexchay/docker-python"
package-mode = false

[tool.poetry.dependencies]
# main dependency group
# poetry install --only main
bump2version = "*"
